### ISSUE TITLE
Help text doesn't explain .env for API credentials

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/telegram-phone-number-checker#13]
Now that this can be installed from pypi directly, it would be good if the helptext (accessed with `telegram-phone-number-checker --help`) provided an explanation of the .env file for credential storage (as in [README.md](https://github.com/bellingcat/telegram-phone-number-checker/blob/main/README.md)).

**Comment by GalenReich** [comment]
It could also include some information on how to get API credentials, and make it clear that it requires Telegram API Credentials.

**Comment by jordan-gillard** [comment]
@GalenReich gimme gimme gimme
