### ISSUE TITLE
Logging in...Attempt 1 at connecting failed: TimeoutError:

### ISSUE THREAD

**Issue by qzinori** [bellingcat/telegram-phone-number-checker#29]
TimeoutError

**Comment by qzinori** [comment]
I use clash's rule agent, but TimeoutError

**Comment by MsFGz** [comment]
我也是求问

**Comment by MsFGz** [comment]
me too !


> I use clash's rule agent, but TimeoutError

**Comment by hantconny** [comment]
add proxy param in login method when creating the client
client = TelegramClient(PHONE_NUMBER, API_ID, API_HASH, proxy=('http', '127.0.0.1', 7890))

**Comment by GalenReich** [comment]
This looks like a local network configuration problem. More information about your network would help us solve this issue.

Judging by the flurry of activity, it may be related to #28

**Comment by GalenReich** [comment]
In the absence of further info, I'm going to close this. But do feel free to add more info and this can be reopened.
