### ISSUE TITLE
Logging in...Attempt 1 at connecting failed: TimeoutError:

### ISSUE THREAD

**Issue by MsFGz** [bellingcat/telegram-phone-number-checker#30]
Logging in...Attempt 1 at connecting failed: TimeoutError:
Attempt 2 at connecting failed: TimeoutError:
Attempt 3 at connecting failed: TimeoutError:
Attempt 4 at connecting failed: TimeoutError:
Attempt 5 at connecting failed: TimeoutError:
Attempt 6 at connecting failed: TimeoutError:

**Comment by GalenReich** [comment]
Closing as duplicate of #29
