### ISSUE TITLE
Add profile photo to response

### ISSUE THREAD

**Issue by xstu25** [bellingcat/telegram-phone-number-checker#31]
Hello. Thanks a lot for your amazing script.

Is there a way to access to Telegram profile picture of the account found ?

Thanks for reply.

**Comment by GalenReich** [comment]
This is a good idea. It is very possible as Telethon [returns the UserProfilePhoto](https://tl.telethon.dev/constructors/user.html) in its existing response. There is also the [download_profile_photo method](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.downloads.DownloadMethods.download_profile_photo) that would be suitable for this.

The behaviour should be accessed through an optional flag (that defaults to not downloading photos), something like:

`telegram-phone-number-checker --download-profile-photos --phone-numbers +1234567890`

The changes would likely need to be made in this block: https://github.com/bellingcat/telegram-phone-number-checker/blob/80d5eb1723047fedbcecabdc21fcf564a95dab63/telegram_phone_number_checker/main.py#L57-L82

We would welcome a PR to implement this! 🎉

**Comment by DouglasKrouth** [comment]
Added here. https://github.com/bellingcat/telegram-phone-number-checker/pull/38
