### ISSUE TITLE
Lost access to my telegram account after trying 1 number

### ISSUE THREAD

**Issue by OnlyMalinka** [bellingcat/telegram-phone-number-checker#39]
I was trying to check some numbers, so i create new app in telegram developers, then use your script to login with code and check one number and when i tried to check another with code, but this time i was loged out from my account from all my devices and now i have only session file from my account. Is there is a way to get my account back from .session file?

**Comment by msramalho** [comment]
Hey @OnlyMalinka I'm sorry to hear that, it's something we should advise against in the README and failed to do so. I've updated it to include a warning on the use of personal accounts. In general, any social media API you're using should be on a sock puppet account to prevent the risk of data loss.

Your ban may be temporary and the best way to proceed is to reach out to Telegram's support. Here's an article with more info on this: https://controlhippo.com/blog/unban-telegram-number/

Good luck :crossed_fingers:
