### ISSUE TITLE
Keep reminding me that I can't connect to 149.154.167.51:443.

### ISSUE THREAD

**Issue by 15653391491** [bellingcat/telegram-phone-number-checker#40]
![image](https://github.com/user-attachments/assets/d1e46dd7-2718-4f02-ad37-6ce10c83d9e1)

**Comment by GalenReich** [comment]
This is likely an error from your internet connection being thrown by telethon and is not something we can solve.

You may need to use a proxy for the tool to work correctly - see #28 for more info
